import { useState } from "react";
import type { BorrowerProfile, IntakeAction, IntakeOptions, IntakeState } from "./api";
import { ErrorBanner } from "./ui";

const fieldsFor = (options: IntakeOptions): [keyof BorrowerProfile, string, string[]?][] => [["entityType", "Entity type", options.entityTypes], ["entityName", "Legal entity name"], ["registrationRef", "Business registration / NIB"], ["taxRef", "Tax registration reference"], ["representativeRole", "Representative capacity", options.representativeRoles], ["authorityRef", "Board mandate / authority reference"], ["commodity", "Goods intended for SRG storage", options.commodities], ["quantityKg", "Intended quantity (kg)"], ["warehouse", "Proposed SRG warehouse", options.warehouses]];
const documents = ["Entity registration", "Tax registration", "Representative authority", "Goods declaration"];

export default function BorrowerOnboarding({ state, options, error, onAction, onComplete, onSwitch, onReset, onHome }: {
  state: IntakeState; options: IntakeOptions; error: string | null; onAction: (action: IntakeAction) => void; onComplete: (profile: BorrowerProfile) => void; onSwitch: () => void; onReset: () => void; onHome: () => void;
}) {
  const [profile, setProfile] = useState(state.borrower.profile);
  const fields = fieldsFor(options);
  return <div className="public-page onboarding-page">
    <header className="public-header compact-header"><button className="wordmark-button" onClick={onHome}>Anora</button><div className="onboarding-header-actions"><button type="button" className="reset-demo" onClick={onReset}>Reset</button><button className="sign-in-button" onClick={onSwitch}>Switch workspace</button></div></header>
    <main className="onboarding-main">
      <header className="onboarding-heading"><div><span className="section-kicker">Borrower registration</span><h1>Register and attest your eligibility.</h1></div></header>
      <div className="onboarding-layout"><section className="onboarding-form">
        {error && <ErrorBanner>{error}</ErrorBanner>}
        <form onSubmit={event => { event.preventDefault(); onComplete(profile); }}>
          <div className="analytics-panel onboarding-section"><div className="status-strip onboarding-privy"><span>Privy account</span><strong>Connected</strong></div><h2>Entity, authority, and goods</h2>
          <fieldset className="onboarding-fields">{fields.map(([key, label, choices]) => <label key={key}>{label}{choices
            ? <select value={String(profile[key])} onChange={event => setProfile({ ...profile, [key]: event.target.value })}>{choices.map(choice => <option key={choice}>{choice}</option>)}</select>
            : <input required maxLength={200} type={key === "quantityKg" ? "number" : "text"} min={key === "quantityKg" ? 1 : undefined} step={key === "quantityKg" ? 1 : undefined} value={profile[key]} onChange={event => setProfile({ ...profile, [key]: key === "quantityKg" ? Number(event.target.value) : event.target.value })} />}</label>)}</fieldset></div>
          <div className="analytics-panel onboarding-section onboarding-verification"><h3>World ID Selfie Check</h3><p>Confirms humanness and a medium-assurance uniqueness signal.</p>
            {/* # WORLD_ID_BACKEND_INTEGRATION: render the backend QR payload here, then replace the demo intake action with its verified proof. */}
            <button type="button" className="secondary-button world-id-button" disabled={state.humanCheck} onClick={() => onAction({ kind: "human" })}>{state.humanCheck ? "World ID verified" : "Verify with World ID"}</button>
            {state.humanCheck && <div className="world-id-qr-slot" role="img" aria-label="Reserved for the World ID QR code"><span>World ID QR code</span><small>Generated by the backend</small></div>}</div>
          <div className="analytics-panel onboarding-section onboarding-verification"><h3>Private attestation</h3>{["Entity KYB evidence", "Representative authority", "Goods and warehouse declaration"].map(label => <div className="onboarding-document" key={label}><span>{label}</span><small>Ready for ZK attestation</small></div>)}<div className="actions"><button type="submit" disabled={!state.humanCheck}>Enter borrower workspace</button></div></div>
        </form>
      </section><aside className="analytics-panel onboarding-summary" aria-label="Registration summary"><h2>Credential preview</h2><div className="onboarding-summary-card"><strong>{profile.entityName}</strong><span>{profile.entityType} · Borrower</span><dl>{fields.filter(([key]) => key !== "entityName" && key !== "entityType").map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{key === "quantityKg" ? `${profile.quantityKg.toLocaleString("en-GB")} kg` : profile[key]}</dd></div>)}</dl></div><h3>Document summary</h3>{documents.map(label => <div className="onboarding-document" key={label}><span>{label}</span></div>)}<h3>Verification scope</h3><p>The credential permits receipt proposals and financing applications. Each receipt and facility still requires separate review.</p></aside></div>
    </main>
  </div>;
}
