import { useState } from "react";

type InstitutionRole = "Capital Provider" | "Compliance";

const PRESET = {
  "Capital Provider": {
    entityName: "Bank Rakyat Sejahtera",
    registrationRef: "OJK-INV-BRS-2026",
    representativeRole: "Treasury & Investment Director",
    authorityRef: "Board mandate BM-2026-091",
    wallet: "0x71B8…93A2",
    credential: "Qualified institutional capital provider",
  },
  Compliance: {
    entityName: "Anora Compliance Operator",
    registrationRef: "PSE-ANORA-2026",
    representativeRole: "Authorized Settlement Officer",
    authorityRef: "Operator charter OPS-2026-007",
    wallet: "0x4C20…18DF",
    credential: "Authorized registry and settlement operator",
  },
};

export default function InstitutionOnboarding({ role, onComplete, onSwitch, onReset, onHome }: {
  role: InstitutionRole; onComplete: () => void; onSwitch: () => void; onReset: () => void; onHome: () => void;
}) {
  const [profile, setProfile] = useState(PRESET[role]);
  const [worldIdVerified, setWorldIdVerified] = useState(false);
  const fields: [keyof typeof profile, string][] = [
    ["entityName", "Legal entity name"], ["registrationRef", "Registration / licence reference"],
    ["representativeRole", "Representative capacity"], ["authorityRef", "Authority reference"],
    ["wallet", "Privy embedded wallet"], ["credential", "Requested credential"],
  ];
  const purpose = role === "Capital Provider" ? "subscribe to and hold permissioned note partitions" : "review evidence, attest eligibility, and control settlement";
  const enterLabel = role === "Capital Provider" ? "Enter capital provider workspace" : "Enter compliance workspace";

  return <div className="public-page onboarding-page">
    <header className="public-header compact-header"><button className="wordmark-button" onClick={onHome}>Anora</button><div className="onboarding-header-actions"><button type="button" className="reset-demo" onClick={onReset}>Reset</button><button className="sign-in-button" onClick={onSwitch}>Switch workspace</button></div></header>
    <main className="onboarding-main">
      <header className="onboarding-heading"><div><span className="section-kicker">{role} registration</span><h1>{role === "Capital Provider" ? "Register and verify eligibility." : "Register and attest your authority."}</h1></div></header>
      <div className="onboarding-layout"><section className="onboarding-form">
        <form onSubmit={event => { event.preventDefault(); if (role !== "Compliance" || worldIdVerified) onComplete(); }}>
          <div className="analytics-panel onboarding-section"><div className="status-strip onboarding-privy"><span>Privy account</span><strong>Connected</strong></div><h2>Organization and authority</h2>
          <fieldset className="onboarding-fields">{fields.map(([key, label]) => <label key={key}>{label}<input required maxLength={200} value={profile[key]} onChange={event => setProfile({ ...profile, [key]: event.target.value })} /></label>)}</fieldset></div>
          {role === "Compliance" && <div className="analytics-panel onboarding-section onboarding-verification"><h3>World ID Selfie Check</h3><p>Confirms the operator is a unique human participant. Organizational authority remains covered by the private credential below.</p>
            {/* # WORLD_ID_BACKEND_INTEGRATION: render the backend QR payload here, then enable registration after server verification. */}
            <button type="button" className="secondary-button world-id-button" disabled={worldIdVerified} onClick={() => setWorldIdVerified(true)}>{worldIdVerified ? "World ID verified" : "Verify with World ID"}</button>
            {worldIdVerified && <div className="world-id-qr-slot" role="img" aria-label="Reserved for the World ID QR code"><span>World ID QR code</span><small>Generated by the backend</small></div>}</div>}
          <div className="analytics-panel onboarding-section onboarding-verification"><h3>Private attestation</h3><p>KYB, representative authority, allowlisting, and the requested role policy are verified without publishing source documents on-chain.</p>{["Entity KYB evidence", "Representative authority", role === "Capital Provider" ? "Investor allowlist and tranche mandate" : "Operator authorization and attestation policy"].map(label => <div className="onboarding-document" key={label}><span>{label}</span><small>Ready for ZK attestation</small></div>)}<div className="actions"><button type="submit" disabled={role === "Compliance" && !worldIdVerified}>{enterLabel}</button></div></div>
        </form>
      </section><aside className="analytics-panel onboarding-summary" aria-label="Registration summary"><h2>Credential preview</h2><div className="onboarding-summary-card"><strong>{profile.entityName}</strong><span>{role}</span><dl><div><dt>Privy wallet</dt><dd>{profile.wallet}</dd></div><div><dt>Credential</dt><dd>{profile.credential}</dd></div><div><dt>Proof disclosure</dt><dd>Policy result and role only</dd></div><div><dt>Source documents</dt><dd>Private and withheld</dd></div></dl></div><h3>Access scope</h3><p>This credential permits {purpose}. It does not bypass per-facility policy, registry, or recipient checks.</p></aside></div>
    </main>
  </div>;
}
